/**
 * Every study listed on softsuave.com/case-studies, in the live page's order.
 *
 * GENERATED from the live page's markup — title, summary, image, platform and
 * category are the live copy verbatim. Images are mirrored into
 * `public/images/case-studies/`; the detail pages are NOT rebuilt here, so
 * each `href` is a live-site path that `SiteLink` sends to softsuave.com.
 *
 * `filters` are the live page's tabs each study appears under. The live page
 * lists two studies (AI Assist, MarketMind) under no tab at all, so they
 * carry no filters here either and show under "All" only, as they do live.
 */

export const caseStudyFacets = ["Healthcare","eCommerce & Marketing","Construction & Manufacturing","Logistics & Transportation","Education & HR Tech","Finance","Telecom","Oil & Gas","On-Demand"] as const;

export type CaseStudyFacet = (typeof caseStudyFacets)[number];

export interface CaseStudyEntry {
  readonly key: string;
  /** The live card's "Category" line. */
  readonly tag: string;
  readonly filters: readonly CaseStudyFacet[];
  readonly title: string;
  readonly body: string;
  readonly image: { readonly src: string; readonly alt: string; readonly width: number; readonly height: number };
  readonly platforms: readonly string[];
  readonly href: string;
}

export const caseStudyEntries: readonly CaseStudyEntry[] = [
  {
    key: "vehicle-intelligence-cs",
    tag: "Transportation",
    filters: ["Logistics & Transportation"],
    title: "A Vision AI Platform for Real-Time Axle Counting & Traffic Monitoring",
    body: "Soft Suave built a real-time computer-vision pipeline that turns top-view highway camera feeds into accurate axle counts, lane-level vehicle tracking, and live congestion insight — with specialised recognition of lifted and floating axles on commercial vehicles, deployed in production across multiple high-traffic sites along a busy highway corridor.",
    image: { src: "/images/case-studies/vehicle-intelligence-cs.webp", alt: "Vehicle Intelligence Platform", width: 642, height: 642 },
    platforms: ["Web"],
    href: "/case-study-vehicle-intelligence",
  },
  {
    key: "neurora-intelligence-cs",
    tag: "Transportation",
    filters: ["Logistics & Transportation"],
    title: "A Platform for Driver Attention, Stress and Safety",
    body: "Soft Suave built an AI-powered Behavioral Intelligence platform that fuses synchronized driving video, eye-gaze, and heart-rate data into automated safety, focus, and stress scores. The system gives driving schools, fleet safety teams, and researchers objective evidence of driver attention — not just what happened, but where a driver looked and when stress took over.",
    image: { src: "/images/case-studies/neurora-intelligence-cs.webp", alt: "Neurora Behavioral Intelligence Platform", width: 642, height: 642 },
    platforms: ["Android","Web"],
    href: "/case-study-neurora-behavioral-intelligence",
  },
  {
    key: "tender-intelligence-cs",
    tag: "Energy / Oil & Gas",
    filters: ["Oil & Gas"],
    title: "AI-Powered Contract & Tender Management Lifecycle Platform",
    body: "Soft Suave built an AI-powered platform automating the full contract and tender lifecycle - from strategy generation through deterministic evaluation to closure - with an immutable, timestamped audit trail, sealed-bid integrity, and full English/Arabic support, delivered entirely on-premises for a leading LNG operator in Oman.",
    image: { src: "/images/case-studies/tender-intelligence-cs.webp", alt: "Tender Intelligence Platform", width: 642, height: 642 },
    platforms: ["Web"],
    href: "/case-study-tender-intelligence",
  },
  {
    key: "shift-sense-cs",
    tag: "Energy / Oil & Gas",
    filters: ["Oil & Gas"],
    title: "An AI-Powered Shift Intelligence and Digital Logbook Platform for LNG Operations",
    body: "Soft Suave delivered ShiftSense, an on-premises AI platform that turns thousands of free-text LNG operational log entries into instant shift summaries and source-cited answers. Built fully air-gapped for a safety-critical plant, it serves English and Arabic users as equals with complete auditability.",
    image: { src: "/images/case-studies/shift-sense-cs.webp", alt: "AI-Powered Shift Intelligence & Digital Logbook Platform", width: 642, height: 642 },
    platforms: ["Web"],
    href: "/case-study-shiftsense-ai-shift-intelligence",
  },
  {
    key: "ai-assist-cs",
    tag: "Logistics",
    filters: [],
    title: "AI-Powered Onboarding and Configuration Assist for a Logistics Management Platform",
    body: "Soft Suave built an always-available AI assistant embedded directly in a logistics management platform, guiding new customers through account setup, warehouse configuration, and carrier connections. Real-time validation and skipped-step detection cut onboarding time in half and reduced support ticket volume.",
    image: { src: "/images/case-studies/ai-assist-cs.webp", alt: "Logistics Management Platform", width: 642, height: 642 },
    platforms: ["Web"],
    href: "/case-study-ai-assist-logistics-onboarding",
  },
  {
    key: "safe-ops-cs",
    tag: "Oil & Gas",
    filters: ["Oil & Gas"],
    title: "AI-Driven Incident Management and Compliance Optimization for Offshore Operations",
    body: "Soft Suave delivered an AI-driven incident management and compliance platform for offshore maritime and energy operations, automating classification, emergency response coordination, and audit-ready documentation. The result: 70% faster incident response and continuous, always-current compliance.",
    image: { src: "/images/case-studies/safe-ops-cs.webp", alt: "AI-Driven Incident Management Platform", width: 642, height: 642 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-safeops-ai-incident-management",
  },
  {
    key: "well-pet-cs",
    tag: "Healthcare",
    filters: ["Healthcare"],
    title: "An AI-Powered Smart Wellness Platform Revolutionizing Pet Healthcare",
    body: "Soft Suave built WellPet, an AI-powered smart wellness platform bringing health assessments, digital medical records, and preventive care reminders into one dashboard for pet parents and veterinarians. Automated document processing cut manual record entry by 90% while keeping vets fully in the picture.",
    image: { src: "/images/case-studies/well-pet-cs.webp", alt: "Pet Care Application", width: 642, height: 642 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-wellpet-ai-smart-wellness-platform",
  },
  {
    key: "post-guard-cs",
    tag: "Marketing & Advertising",
    filters: ["eCommerce & Marketing"],
    title: "An AI-Powered Compliance Analysis Platform for Influencer Marketing",
    body: "Soft Suave built an AI-powered compliance platform that automatically evaluates sponsored social media content — text, images, and video — against an organization's ingested rulebook, returning a clear verdict with cited violations in seconds instead of days of manual review.",
    image: { src: "/images/case-studies/post-guard-cs.webp", alt: "AI-Powered Influencer Marketing Platform", width: 642, height: 642 },
    platforms: ["Web"],
    href: "/case-study-postguard-compliance-ai",
  },
  {
    key: "marketmind-cs",
    tag: "FinTech & Capital Markets",
    filters: [],
    title: "AI-Native Multi-Tenant Market Intelligence for Traders and Analysts",
    body: "Soft Suave delivered MarketMind, an AI-native multi-tenant market intelligence platform where an AI orchestrator coordinates specialised agents so traders and analysts get plain-English answers grounded in their firm's own data. Built with strict tenant isolation and financial-institution-grade security from day one.",
    image: { src: "/images/case-studies/marketmind-cs.webp", alt: "Multi-Tenant Market Intelligence Platform", width: 642, height: 642 },
    platforms: ["Web"],
    href: "/case-study-marketmind-ai-market-intelligence",
  },
  {
    key: "brand-forge-cs",
    tag: "Energy / Oil & Gas",
    filters: ["Oil & Gas"],
    title: "An AI Content Production Programme for Enterprise Strategic Communications",
    body: "Soft Suave delivered eight AI-powered content production use cases for a national energy company's strategic communications function - covering campaign assets, multichannel copy, speechwriting, and bilingual Arabization - all built inside the client's own Microsoft and Azure ecosystem with mandatory human approval on every workflow.",
    image: { src: "/images/case-studies/brand-forge-cs.webp", alt: "FREELANCER PLATFORM", width: 642, height: 642 },
    platforms: ["Web"],
    href: "/case-study-brand-forge",
  },
  {
    key: "hire-voice-cs",
    tag: "HR Tech",
    filters: ["Education & HR Tech"],
    title: "Hire Voice — An AI-Powered Voice Interview Platform for Scalable Technical Hiring",
    body: "Soft Suave built an AI bot that conducts spoken technical interviews end-to-end in the browser — asking questions aloud, understanding answers in real time, and scoring every transcript into a shareable PDF report — while interviewers stay in control throughout.",
    image: { src: "/images/case-studies/hire-voice-cs.webp", alt: "Personalized eCommerce Platform", width: 642, height: 642 },
    platforms: ["Web"],
    href: "/case-study-hire-voice",
  },
  {
    key: "ecommerce-3",
    tag: "eCommerce",
    filters: ["eCommerce & Marketing"],
    title: "Subscription Management for Customer Growth",
    body: "Soft Suave offers a powerful platform that streamlines subscription workflows, analyzes customer behavior, and automates renewals—helping businesses boost retention, drive growth, and deliver seamless subscription experiences.",
    image: { src: "/images/case-studies/ecommerce-3.webp", alt: "Subscription Management Platform", width: 618, height: 571 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-subscription-management-for-customer-growth",
  },
  {
    key: "ecommerce-1",
    tag: "eCommerce",
    filters: ["eCommerce & Marketing"],
    title: "Comprehensive eCommerce for Retail",
    body: "Soft Suave delivered an end-to-end eCommerce solution tailored for the retail industry—enabling seamless product management, secure transactions, personalized shopping experiences, and real-time analytics to drive growth and customer engagement.",
    image: { src: "/images/case-studies/ecommerce-1.webp", alt: "Comprehensive eCommerce Platform for Retail", width: 642, height: 593 },
    platforms: ["Android","iOS"],
    href: "/case-study-comprehensive-ecommerce-for-retail",
  },
  {
    key: "ecommerce-2",
    tag: "eCommerce",
    filters: ["eCommerce & Marketing"],
    title: "Intuitive Online Shopping Platform",
    body: "Soft Suave built a user-friendly online shopping platform that offers smooth navigation, personalized recommendations, and secure checkout—enhancing the customer experience and boosting conversion rates for retailers.",
    image: { src: "/images/case-studies/ecommerce-2.webp", alt: "Intuitive Online Shopping Platform", width: 642, height: 593 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-intuitive-online-shopping-platform",
  },
  {
    key: "ecommerce-p",
    tag: "eCommerce",
    filters: ["eCommerce & Marketing"],
    title: "Personalized One-Stop Solution for eCommerce Industry",
    body: "Soft Suave created an app to satisfy multiple needs to seamlessly give effective eCommerce solutions to customers. Specifically, the client wanted mobile applications that would enable customers to make fast decisions and lead them to make a purchase.",
    image: { src: "/images/case-studies/ecommerce-p.png", alt: "Personalized eCommerce Platform", width: 600, height: 496 },
    platforms: ["Android","iOS"],
    href: "/case-study-personalized-ecommerce-platform",
  },
  {
    key: "healthcare-1",
    tag: "Healthcare",
    filters: ["Healthcare"],
    title: "AI Optimization in Healthcare",
    body: "Leveraging artificial intelligence, Soft Suave delivers innovative healthcare solutions that enhance diagnostic accuracy, optimize treatment plans, and streamline hospital operations. Our AI-driven systems empower providers to make faster, data-backed decisions, improving patient outcomes and operational efficiency.",
    image: { src: "/images/case-studies/healthcare-1.webp", alt: "AI Optimization in Healthcare", width: 642, height: 593 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-ai-optimization-in-healthcare",
  },
  {
    key: "patient-2-new",
    tag: "Healthcare",
    filters: ["Healthcare"],
    title: "Remote Platform to Connect Doctors and Patients from Anywhere",
    body: "Soft Suave made an app that connects doctors and patients from anywhere to schedule and accept appointments and have an online consultation using video call facilities. The app simplified the risk of rushing to the hospital for small emergency consultations.",
    image: { src: "/images/case-studies/patient-2-new.png", alt: "Online Consultation Platform for Doctors", width: 650, height: 600 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-online-consultation-platform-for-doctors",
  },
  {
    key: "telemedicine-2",
    tag: "Healthcare",
    filters: ["Healthcare"],
    title: "Time-saving Video Calling App for Healthcare Industry",
    body: "Soft Suave developed an efficient video calling app for instant consultations, to save time, and to get fast solutions. A video calling facility designed specifically for doctor-patient inquiries to keep health on track by scheduling doctor appointments.",
    image: { src: "/images/case-studies/telemedicine-2.png", alt: "Telehealth Consultation Platform for Doctors", width: 650, height: 600 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-telehealth-consultation-platform-for-doctors",
  },
  {
    key: "tele-app",
    tag: "Healthcare",
    filters: ["Healthcare"],
    title: "Custom Telehealth App for Doctor Consultation",
    body: "Our client was a MedTech start-up and leading provider of online healthcare across borders. The client wanted to democratize access to advanced healthcare management for everyone with the help of mobile solutions and promote healthcare through innovation in telemedicine.",
    image: { src: "/images/case-studies/tele-app.png", alt: "Custom Telehealth App for Doctor Consultation", width: 557, height: 530 },
    platforms: ["Android","iOS"],
    href: "/case-study-online-consultation-platform-for-doctors",
  },
  {
    key: "on-demand-15",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "AI-Driven Equipment & Workforce Optimization",
    body: "Soft Suave delivered an AI-powered solution that enables intelligent equipment tracking, accurate workforce management, automated machine data capture, and real-time insights into asset performance and operational efficiency—empowering businesses to optimize field operations and reduce downtime.",
    image: { src: "/images/case-studies/on-demand-15.webp", alt: "Integrated Billing Platform", width: 642, height: 593 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-ai-driven-equipment-&-workforce-optimization",
  },
  {
    key: "on-demand-16",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Streamlining Publication Workflows with Integrated Tracking",
    body: "Soft Suave built a centralized platform to streamline article and issue tracking, simplify user and journal management, automate production workflows, and enhance visibility into tasks, milestones, and workload distribution—enabling the client to optimize their publication process efficiently.",
    image: { src: "/images/case-studies/on-demand-16.webp", alt: "Integrated Billing Platform", width: 642, height: 593 },
    platforms: ["Web"],
    href: "/case-study-streamlining-publication-workflows-with-integrated-tracking",
  },
  {
    key: "on-demand-14",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Smart Warranty and Document Management App",
    body: "Soft Suave delivers an intelligent app that automates warranty tracking, organizes critical documents, and provides real-time notifications—helping users manage assets efficiently and protect investments with ease and accuracy.",
    image: { src: "/images/case-studies/on-demand-14.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-smart-warranty-and-document-management-app",
  },
  {
    key: "on-demand-13",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "AI-Powered Business Intelligence Insights",
    body: "Soft Suave provides an advanced AI-driven platform that analyzes complex data, uncovers actionable insights, and automates reporting—enabling organizations to make smarter, faster business decisions with confidence and precision.",
    image: { src: "/images/case-studies/on-demand-13.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Web"],
    href: "/case-study-ai-powered-business-intelligence-insights",
  },
  {
    key: "on-demand-12",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "AI Chatbot for Engagement and Secure Transactions",
    body: "Soft Suave offers a cutting-edge AI chatbot that enhances customer engagement, facilitates secure transactions, and automates responses—helping businesses deliver seamless, trustworthy interactions with speed and reliability.",
    image: { src: "/images/case-studies/on-demand-12.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Web"],
    href: "/case-study-ai-chatbot-for-engagement-and-secure-transactions",
  },
  {
    key: "on-demand-11",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "AI-Powered Multi-Cloud Management",
    body: "Soft Suave delivers an advanced AI-driven platform that monitors, optimizes, and automates multi-cloud environments in real time—empowering organizations to manage complex infrastructures with agility, security, and cost-efficiency.",
    image: { src: "/images/case-studies/on-demand-11.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Android","iOS"],
    href: "/case-study-ai-powered-multi-cloud-management",
  },
  {
    key: "on-demand-10",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Smart Digital Signage with Advanced Ad Scheduling",
    body: "Soft Suave provides an intelligent digital signage solution that optimizes ad scheduling, personalizes content in real time, and automates display management—helping businesses engage audiences with timely, targeted messaging and maximize advertising impact.",
    image: { src: "/images/case-studies/on-demand-10.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-smart-digital-signage-with-advanced-ad-scheduling",
  },
  {
    key: "on-demand-9",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Tech-Driven Workforce Development Platform",
    body: "Soft Suave delivers an innovative AI-powered platform that personalizes skill development, tracks progress in real time, and automates training workflows—enabling organizations to build agile, future-ready workforces with efficiency and precision.",
    image: { src: "/images/case-studies/on-demand-9.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-tech-driven-workforce-development-platform",
  },
  {
    key: "on-demand-8",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Optimizing Influencer and Brand Collaborations",
    body: "Soft Suave offers an intelligent platform that streamlines influencer and brand partnerships by analyzing performance, automating workflows, and maximizing engagement—helping businesses achieve impactful, data-driven collaborations with ease and efficiency.",
    image: { src: "/images/case-studies/on-demand-8.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-optimizing-influencer-and-brand-collaborations",
  },
  {
    key: "on-demand-7",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "AI-Driven Cybersecurity Automation",
    body: "Soft Suave delivers an advanced AI-powered solution that automates threat detection, analyzes anomalies in real time, and orchestrates rapid responses—empowering organizations to stay ahead of cyber threats with agility and precision.",
    image: { src: "/images/case-studies/on-demand-7.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Web"],
    href: "/case-study-ai-driven-cybersecurity-automation",
  },
  {
    key: "on-demand-6",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "AI-Powered Cyber Threat Detection",
    body: "Soft Suave developed an advanced AI-driven cybersecurity solution that detects threats in real-time, analyzes anomalies, and automates responses—helping organizations stay ahead of evolving cyber risks with speed and precision.",
    image: { src: "/images/case-studies/on-demand-6.webp", alt: "Integrated Billing Platform", width: 642, height: 593 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-ai-powered-cyber-theart-detection",
  },
  {
    key: "on-demand-5",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Smart Movie Ticketing with Real-Time Booking",
    body: "Soft Suave designed an intelligent movie ticketing system that offers real-time seat availability, secure payments, and seamless booking—enhancing the cinema experience for both customers and theater operators.",
    image: { src: "/images/case-studies/on-demand-5.webp", alt: "Integrated Billing Platform", width: 642, height: 593 },
    platforms: ["Web"],
    href: "/case-study-smart-movie-ticketing-with-real-time-booking",
  },
  {
    key: "on-demand-4",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Custom Business Management Platform",
    body: "Soft Suave developed a fully customizable business management platform that unifies operations—from sales and inventory to HR and finance—empowering organizations to streamline workflows and scale with confidence.",
    image: { src: "/images/case-studies/on-demand-4.webp", alt: "Integrated Billing Platform", width: 642, height: 593 },
    platforms: ["Web"],
    href: "/case-study-custom-business-management-platform",
  },
  {
    key: "on-demand-3",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Restaurant Workflow Optimization",
    body: "Soft Suave built a smart restaurant management solution that optimizes order processing, kitchen operations, and staff coordination—boosting efficiency, reducing wait times, and enhancing the overall dining experience.",
    image: { src: "/images/case-studies/on-demand-3.webp", alt: "Tech-Driven Financial Modeling", width: 642, height: 593 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-restaurant-workflow-optimization",
  },
  {
    key: "on-demand-2",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Project & Compliance Workflow Transformation",
    body: "Soft Suave delivered a tailored solution to streamline project management and automate compliance workflows—enhancing transparency, reducing risks, and improving operational efficiency across regulated environments.",
    image: { src: "/images/case-studies/on-demand-2.webp", alt: "JOB PROGRESS TRACKING", width: 642, height: 593 },
    platforms: ["Web"],
    href: "/case-study-project-&-compliance-workflow-transformation",
  },
  {
    key: "on-demand-1",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Digital Advertising in Public Spaces",
    body: "Soft Suave developed a dynamic digital advertising solution that enables real-time content management, location-based targeting, and performance analytics—transforming public spaces into impactful marketing channels.",
    image: { src: "/images/case-studies/on-demand-1.webp", alt: "FREELANCER PLATFORM", width: 642, height: 593 },
    platforms: ["Web"],
    href: "/case-study-digital-advertising-in-public-spaces",
  },
  {
    key: "solar-mapping",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Area Mapping Solution For A Solar Business",
    body: "Our client, established in 2020, specializes in providing solar energy solutions, emphasizing home energy efficiency and sustainable power. Established to help homeowners transition to cleaner energy forms, they offer comprehensive consultations and installations, ensuring energy savings and reduced utility bills.",
    image: { src: "/images/case-studies/solar-mapping.webp", alt: "Area Mapping Solution For A Solar Business", width: 557, height: 540 },
    platforms: ["Web"],
    href: "/case-study-area-mapping-solution",
  },
  {
    key: "ticket-management",
    tag: "On-Demand",
    filters: ["On-Demand"],
    title: "Advanced Ticket Management App for Risk-Free Transactions",
    body: "Soft Suave developed futuristic mobile and web applications, you can manage tickets and customer relationships on the go. We Advanced their needs and made the existing application more user-friendly and simple to manage with cost-effective solutions.",
    image: { src: "/images/case-studies/ticket-management.png", alt: "Ticket Management System Development", width: 600, height: 496 },
    platforms: ["Android","Web"],
    href: "/case-study-ticket-management-system",
  },
  {
    key: "legal-violation",
    tag: "On-Demand",
    filters: ["On-Demand","Logistics & Transportation"],
    title: "Violation Tracking Application to Conserve National Security",
    body: "To keep tracking the illegal activities happening on the street, Soft Suave developed a Legal Violation tracking that helps them to prevent unlawful activities in the US. Our clients who are US-based government agencies use this application to conserve national security.",
    image: { src: "/images/case-studies/legal-violation.png", alt: "LEGAL VIOLATION TRACKING APPLICATION", width: 600, height: 496 },
    platforms: ["Android","iOS"],
    href: "/case-study-legal-violation-tracking-application",
  },
  {
    key: "job",
    tag: "Construction",
    filters: ["Construction & Manufacturing"],
    title: "Effective Tool to track the Jobs or Projects for the Customers",
    body: "A standout job tracking solution app made by Soft Suave to ease the complex processes, for the customers to use and track the individual projects and Jobs more flexibly.",
    image: { src: "/images/case-studies/job.webp", alt: "Job Progress Tracking App Development", width: 557, height: 570 },
    platforms: ["Android","iOS"],
    href: "/case-study-job-progress-tracking",
  },
  {
    key: "crm-tracking-1",
    tag: "Construction",
    filters: ["Construction & Manufacturing"],
    title: "Real Estate CRM Platform for better Process Tracking",
    body: "Soft Suave designed and developed a real estate Management App Real estate owners can use a CRM application for property management and executing a 360-degree property view across multiple platforms including Web, iOS, and Desktop. This will help real estate owners to keep track of and manage their processes.",
    image: { src: "/images/case-studies/crm-tracking-1.png", alt: "CRM APPLICATION FOR REAL ESTATE MANAGEMENT", width: 650, height: 650 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-crm-application-for-real-estate",
  },
  {
    key: "logistics-3",
    tag: "Logistics",
    filters: ["Logistics & Transportation"],
    title: "ParkSafe Community Vehicle Alert App",
    body: "Soft Suave developed a smart community-driven app that detects suspicious vehicle activity, sends real-time alerts, and fosters neighborhood safety—empowering residents to protect their surroundings with speed and collaboration.",
    image: { src: "/images/case-studies/logistics-3.webp", alt: "Web Scraping Solution", width: 618, height: 571 },
    platforms: ["Web"],
    href: "/case-study-parksafe-community-vehicle-alert-app",
  },
  {
    key: "logistics-1",
    tag: "Logistics",
    filters: ["Logistics & Transportation"],
    title: "Centralized Shipment Tracking",
    body: "Soft Suave developed a centralized shipment tracking system that provides real-time visibility, automated updates, and streamlined logistics coordination—empowering businesses to manage deliveries efficiently and enhance customer satisfaction.",
    image: { src: "/images/case-studies/logistics-1.webp", alt: "Web Scraping Solution", width: 642, height: 593 },
    platforms: ["Web"],
    href: "/case-study-centralized-shipment-tracking",
  },
  {
    key: "logistics-2",
    tag: "Logistics",
    filters: ["Logistics & Transportation"],
    title: "Scalable Delivery Management for Logistics",
    body: "Soft Suave engineered a robust delivery management platform designed for logistics providers—offering route optimization, real-time tracking, and scalable operations to meet growing demand with improved speed and accuracy.",
    image: { src: "/images/case-studies/logistics-2.webp", alt: "Web Scraping Solution", width: 642, height: 593 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-scalable-delivery-mangement-for-logistics",
  },
  {
    key: "web-scrapping-logi",
    tag: "Logistics",
    filters: ["Logistics & Transportation"],
    title: "Web Scraping Solution For Logistics Business",
    body: "Our client is a cloud-based logistics management solution targeting businesses that ship goods, including manufacturers, retailers, and e-commerce companies.",
    image: { src: "/images/case-studies/web-scrapping-logi.webp", alt: "Web Scraping Solution", width: 557, height: 540 },
    platforms: ["Web"],
    href: "/case-study-web-scraping-solution",
  },
  {
    key: "heling-ride",
    tag: "Logistics",
    filters: ["Logistics & Transportation"],
    title: "Ride-hailing Service Application for Flexible Booking and Quality Rides",
    body: "We built a mobile app for a ride-hailing for a logistics company that operates on a bid basis. This client provided taxi services in the United States. Customers in the United States received seamless and quality taxi services from the company with this taxi application",
    image: { src: "/images/case-studies/heling-ride.png", alt: "LOGISTICS RIDE HAILING APPLICATION", width: 557, height: 570 },
    platforms: ["Android","Web"],
    href: "/case-study-logistics-ride-hailing-application",
  },
  {
    key: "education-2",
    tag: "Education",
    filters: ["Education & HR Tech"],
    title: "High-Performance LMS for Education",
    body: "Soft Suave engineered a high-performance Learning Management System designed to deliver seamless course management, interactive learning experiences, and real-time performance tracking—empowering educators and learners in a digital-first environment.",
    image: { src: "/images/case-studies/education-2.webp", alt: "SALESFORCE TELEPHONE APP INTEGRATION", width: 642, height: 593 },
    platforms: ["Web"],
    href: "/case-study-high-performance-lms-for-education",
  },
  {
    key: "education-1",
    tag: "Education",
    filters: ["Education & HR Tech"],
    title: "AI-Powered Education Solutions",
    body: "Soft Suave created intelligent education solutions driven by AI to personalize learning paths, automate assessments, and deliver actionable insights—enhancing engagement, efficiency, and academic outcomes for students and institutions.",
    image: { src: "/images/case-studies/education-1.webp", alt: "SALESFORCE TELEPHONE APP INTEGRATION", width: 642, height: 593 },
    platforms: ["Web"],
    href: "/case-study-ai-powered-education-solutions",
  },
  {
    key: "education-3",
    tag: "Education",
    filters: ["Education & HR Tech"],
    title: "Cloud-Based Campus Management",
    body: "Soft Suave developed a scalable cloud-based campus management platform that automates academic and administrative processes—centralizing student data, enhancing collaboration, and ensuring seamless communication across departments.",
    image: { src: "/images/case-studies/education-3.webp", alt: "SALESFORCE TELEPHONE APP INTEGRATION", width: 642, height: 593 },
    platforms: ["Web"],
    href: "/case-study-cloud-based-campus-management",
  },
  {
    key: "finance-7",
    tag: "Finance",
    filters: ["Finance"],
    title: "SaaS Platform for Corporate Banking",
    body: "Soft Suave delivers a secure, scalable SaaS solution that streamlines corporate banking operations, automates workflows, and provides real-time financial insights—empowering institutions to serve business clients with speed, compliance, and agility.",
    image: { src: "/images/case-studies/finance-7.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-saas-platform-for-corporate-banking",
  },
  {
    key: "finance-6",
    tag: "Finance",
    filters: ["Finance"],
    title: "HealthPass Wellness Subscriptions in Banking",
    body: "Soft Suave introduces an integrated wellness subscription platform that enables banks to offer personalized health benefits, track engagement, and boost customer loyalty—bridging financial services and well-being with innovation and care.",
    image: { src: "/images/case-studies/finance-6.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Android","iOS"],
    href: "/case-study-healthpass-wellness-subscriptions-in-banking",
  },
  {
    key: "finance-5",
    tag: "Finance",
    filters: ["Finance"],
    title: "Savings Solution for Better Financial Management",
    body: "Soft Suave offers a smart savings platform that automates goal-based saving, tracks spending habits, and delivers personalized insights—helping users build financial stability with ease, discipline, and confidence.",
    image: { src: "/images/case-studies/finance-5.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Web"],
    href: "/case-study-savings-solution-for-better-financial-management",
  },
  {
    key: "finance-4",
    tag: "Finance",
    filters: ["Finance"],
    title: "All-in-One Financial Management App",
    body: "Soft Suave developed a comprehensive app that centralizes budgeting, expense tracking, investment insights, and bill management—empowering users to take control of their finances with clarity, convenience, and confidence.",
    image: { src: "/images/case-studies/finance-4.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-all-in-one-financial-management-app",
  },
  {
    key: "finance-3",
    tag: "Finance",
    filters: ["Finance"],
    title: "High-Performance Trading Platform",
    body: "Soft Suave delivers a robust trading platform engineered for speed, real-time analytics, and secure transactions—empowering investors and institutions to execute trades with precision, reliability, and confidence.",
    image: { src: "/images/case-studies/finance-3.webp", alt: "Integrated Billing Platform", width: 618, height: 571 },
    platforms: ["Web"],
    href: "/case-study-high-performance-trading-platform",
  },
  {
    key: "finance-1",
    tag: "Finance",
    filters: ["Finance"],
    title: "Blockchain Digital Currency Platform",
    body: "Soft Suave developed a secure and scalable blockchain-based digital currency platform that enables seamless transactions, transparent ledger management, and decentralized financial operations—empowering businesses with next-gen fintech capabilities.",
    image: { src: "/images/case-studies/finance-1.webp", alt: "Integrated Billing Platform", width: 642, height: 593 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-blockchain-digital-currency-platform",
  },
  {
    key: "finance-2",
    tag: "Finance",
    filters: ["Finance"],
    title: "Optimizing Corporate Banking with the Rocket Account Solution",
    body: "Soft Suave's Rocket Account Solution streamlines corporate banking by automating financial processes, enhancing security, and delivering real-time insights. Designed for scalability and speed, it empowers businesses to manage accounts and transactions with greater efficiency and control.",
    image: { src: "/images/case-studies/finance-2.webp", alt: "Integrated Billing Platform", width: 642, height: 593 },
    platforms: ["Android","iOS","Web"],
    href: "/case-study-corporate-banking-solution",
  },
  {
    key: "digital-banking-2",
    tag: "Finance",
    filters: ["Finance"],
    title: "Building a Highly Secured One-stop Digital Banking Solution",
    body: "The Client is one of the first neo-banking companies based in the Philippines with branches in Singapore and India. They want to expand their service through a mobile application that sits on everyone's phone as a secured banking platform.",
    image: { src: "/images/case-studies/digital-banking-2.png", alt: "Digital Banking App Development", width: 557, height: 580 },
    platforms: ["Android","Web","Database"],
    href: "/onestop-digital-banking-solution",
  },
  {
    key: "manufacturing",
    tag: "Manufacturing",
    filters: ["Construction & Manufacturing"],
    title: "Digitizing Product Inspections",
    body: "Soft Suave created a digital inspection platform that streamlines quality checks, captures real-time data, and ensures compliance—reducing manual errors and accelerating the product validation process across industries.",
    image: { src: "/images/case-studies/manufacturing.webp", alt: "Area Mapping Solution For A Solar Business", width: 642, height: 593 },
    platforms: ["Android","iOS"],
    href: "/case-study-digitizing-product-inspections",
  },
  {
    key: "sales-fo-3",
    tag: "Telecom",
    filters: ["Telecom"],
    title: "A Cloud-based Integration Telephone App to Reduce Operating Costs",
    body: "Soft Suave developed an app that integrates with Salesforce and provides seamless telephone communication. The app’s powerful cloud-based in-company upshot with extensive integration capabilities cuts operating costs and offers great flexibility.",
    image: { src: "/images/case-studies/sales-fo-3.png", alt: "SALESFORCE TELEPHONE APP INTEGRATION", width: 557, height: 550 },
    platforms: ["Web"],
    href: "/case-study-salesforce-telephone-app-integration",
  },
];
