import 'server-only';
import type { Metadata } from 'next';
import { absoluteUrl } from '@/lib/seo/metadata';
import { brand } from './content';
import { HOME_LIVE_JSON_LD } from './home-live-schema';
import { pageRobots } from '@/lib/flags';

/**
 * Metadata and structured data for the homepage.
 *
 * The 11 Sep review found the page shipping neither: no Open Graph or Twitter
 * tags (the group layout declared title, description and canonical and stopped
 * there, so a shared link had no card), and no JSON-LD at all, while every
 * landing page beside it emits both. This module is the homepage's equivalent of
 * `sectors/seo.ts` and `hire-roles/page-meta.ts`.
 *
 * It lives here rather than in the route so the page file stays a composition of
 * sections, and it is `server-only` because `absoluteUrl` is.
 *
 * The JSON-LD is a verbatim mirror of softsuave.com's homepage — see
 * `home-live-schema.ts`. The marketing layout emits the site-wide
 * Organization and WebSite (`lib/seo/organization.ts`) on every other page but
 * not this one (`SiteGraph`), so this page's schema is the live page's and
 * nothing more.
 */

/* The SEO title and description as supplied for the homepage (30 Sep): 44 and
   113 characters, inside the ~60 / ~160 where Google truncates on desktop. */
const TITLE = 'Custom AI Solutions to Empower Your Business';

const DESCRIPTION =
  "Discover how Soft Suave's custom AI solutions can transform your business " +
  'operations and drive innovation';

/* The link-preview card (1 Oct request: "add Social Share Preview image"): a
   frame of the hero's own intro video behind the page's title, set in the
   page's fonts, at 1200×630. It replaces a text-only card generated by `/og`.
   softsuave.com's own og:image is 840×439, under the 1200×630 a large preview
   is drawn at, and carries the retired "The smart way..." tagline, so it is
   not reused. */
const OG_IMAGE = {
  url: absoluteUrl('/assets/images/home-og.webp'),
  width: 1200,
  height: 630,
  alt: 'Custom AI Solutions to Empower Your Business - Soft Suave',
};

export const homeMetadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: '/' },
  robots: pageRobots,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: absoluteUrl('/'),
    siteName: brand.name,
    type: 'website',
    images: [OG_IMAGE],
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
    images: [OG_IMAGE.url],
  },
};

/**
 * The homepage's JSON-LD: softsuave.com's homepage blocks, copied verbatim —
 * Service and LocalBusiness, in the live page's order. See
 * `home-live-schema.ts` for why they are kept exactly as the live site has
 * them, quirks included. The page renders each as its own <script>, as live
 * does, rather than one array.
 *
 * Copies, so a caller mutating the result cannot edit the source for the next
 * render.
 */
export function homeJsonLd(): Record<string, unknown>[] {
  return HOME_LIVE_JSON_LD.map((node) => structuredClone(node));
}
